### ISSUE TITLE
Handle Error in Formula Processing for Xlsx

### ISSUE THREAD

**Issue by pllevy173** [PHPOffice/PhpSpreadsheet#1382]
This is:

```
- [x] a bug report
```

### What is the expected behavior?
I try to load an xlsx file and then to write it without any modification.
Just to check if load/write works.

### What is the current behavior?
Unexpected error in logs.
```
 [20-Feb-2020 08:42:40] WARNING: [pool www] child 70 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: EPC!A1 -> EPC!O1 -> Formula Error: An unexpected error occured in /app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php:277"
[20-Feb-2020 08:42:40] WARNING: [pool www] child 70 said into stderr: "Stack trace:"
[20-Feb-2020 08:42:40] WARNING: [pool www] child 70 said into stderr: "#0 /app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(1080): PhpOffice\PhpSpreadsheet\Cell\Cell->getCalculatedValue()"
[20-Feb-2020 08:42:40] WARNING: [pool www] child 70 said into stderr: "#1 /app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(1030): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeCell(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), 'A1', Array)"
[20-Feb-2020 08:42:40] WARNING: [pool www] child 70 said into stderr: "#2 /app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(76): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeSheetData(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), Array)"
[20-Feb-2020 08:42:40] WARNING: [pool www] child 70 said into stderr: "#3 /app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php(281): PhpOffic..."
[php-fpm:access] 127.0.0.1 -  20/Feb/2020:08:42:40 +0000 "GET /index.php" 500 /app/index.php 145.239 6144 103.28%
2020/02/20 08:42:40 [error] 69#69: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: EPC!A1 -> EPC!O1 -> Formula Error: An unexpected error occured in /app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php:277
Stack trace:
#0 /app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(1080): PhpOffice\PhpSpreadsheet\Cell\Cell->getCalculatedValue()
#1 /app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(1030): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeCell(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), 'A1', Array)
#2 /app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(76): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeSheetData(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), Array)
#3 /app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php(281): PhpOffice\PhpSpr" while reading response header from upstream, client: 192.168.192.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:4455"
192.168.192.1 - - [20/Feb/2020:08:42:40 +0000] "GET / HTTP/1.1" 500 5 "-" "Links (2.14; Linux

```

### What are the steps to reproduce?
I can reproduce systematically with a specific xlsm file.
But I cannot manage to create from a blank file the same behavior.

The Cell O1 indicated contains follocing formula (extracted from the xml of sheet1)
`IF(ISBLANK(Q1),"",VLOOKUP($Q1,BaseRefs[],2,FALSE))`

BaseRefs is a table on sheet2

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.2.27 
phpspreadsheet latest git version/master branch of 20th Feb
It looks like https://github.com/PHPOffice/PhpSpreadsheet/pull/1267

**Comment by oleibman** [comment]
I am not sure what the square brackets in your formula are supposed to do. Excel says there is an error in the formula when I try to enter it exactly as you specify. However, when I remove the square brackets:
IF(ISBLANK(Q1),"",VLOOKUP($Q1,BaseRefs,2,FALSE))
Excel accepts that formula. And when I save that workbook, and open it with PhpSpreadsheet, and then write the result to a new file, everything appears to be working correctly. See attached file (if I've done it correctly).
[xspreadsheetbug.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4257131/xspreadsheetbug.xlsx)
