### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by LoekvanKooten** [PHPOffice/PhpSpreadsheet#1637]
This is:

```
- [ ] a bug report
```

### What is the expected behavior?
XLS file exports neatly.

### What is the current behavior?
Export crashes halfway.

### What are the steps to reproduce?
Export the file.
`$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);`
on
Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.12

First time I encounter this issue. Could it be memory-related?

`Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Dialogs!AA2 -> internal error in C:\xampp\htdocs\ModernMT\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Cell\Cell.php:270 Stack trace: #0 C:\xampp\htdocs\ModernMT\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\Worksheet.php(1113): PhpOffice\PhpSpreadsheet\Cell\Cell->getCalculatedValue() #1 C:\xampp\htdocs\ModernMT\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\Worksheet.php(1183): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeCellFormula(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), '=IFERROR(__xlud...', Object(PhpOffice\PhpSpreadsheet\Cell\Cell)) #2 C:\xampp\htdocs\ModernMT\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\Worksheet.php(1040): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeCell(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), 'AA2', Array) #3 C:\xampp\htdocs\ModernMT\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsh in C:\xampp\htdocs\ModernMT\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Cell\Cell.php on line 270
`

**Comment by LoekvanKooten** [comment]
Said cell (AA2) is empty and contains nothing special.

**Comment by LoekvanKooten** [comment]
Cause found. The cell did contain something after all:
=ALS.FOUT(__xludf.DUMMYFUNCTION("UNIQUE(Z2:Z3373)");"")
(ALS.FOUT is the Dutch equivalent for I think it's just IF.ERROR in English.)

I think this formula can be handled better than just an Internal Error?

Making the cell empty solved the issue.

**Comment by oleibman** [comment]
Removing stale label. Formulas of this type are generated by Google Sheets when it exports a spreadsheet in Xlsx format. I am unable to duplicate the Internal Error, but a lot of time and software changes have happened in the meantime. PhpSpreadsheet evaluates the cell as a `#NAME?` error. I will submit a PR soon to handle it better.
