### ISSUE TITLE
Fatal error: Uncaught ErrorException: Undefined index: Ra44a55188c4e422b in /var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx/Hyperlinks.php:44 Stack trace: #0

### ISSUE THREAD

**Issue by JustZacca** [PHPOffice/PhpSpreadsheet#1722]
Hi, I'm new to PHPSpreadsheet and I'm having an issue importing a file (all the other files works, only this one doesn't). 

### **The error is:** 

> Fatal error: Uncaught ErrorException: Undefined index: Ra44a55188c4e422b in /var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx/Hyperlinks.php:44 Stack trace: #0 /var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx/Hyperlinks.php(44): exceptions_error_handler(8, 'Undefined index...', '/var/www/html/v...', 44, Array) #1 /var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx/Hyperlinks.php(32): PhpOffice\PhpSpreadsheet\Reader\Xlsx\Hyperlinks->setHyperlink(Object(SimpleXMLElement), Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet)) #2 /var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php(822): PhpOffice\PhpSpreadsheet\Reader\Xlsx\Hyperlinks->setHyperlinks(Object(SimpleXMLElement)) #3 /var/www/html/Static/lib/data.php(129): PhpOffice\PhpSpreadsheet\Reader\Xlsx->load('/var/www/html/S...') #4 /var/www/html/Static/lib/data.php(46): Data->convertCSV() #5 /var/www/html/upload.php(14): Data->takeFile('UBISOFT SpA (20...') #6 {main} in /var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx/Hyperlinks.php on line 44 

### **Which part of the code produces the error?**
```
<?php $reader = IOFactory::createReader("Xlsx");
            $spreadsheet = $reader->load($this->rawFile);

            // Export to CSV file.
            $writer = IOFactory::createWriter($spreadsheet, "Csv");
            $writer->setSheetIndex(0);   // Select which sheet to export.
            $writer->setDelimiter('');  // Set delimiter.
            $writer->save($this->csvFile); ?>
```

**Please I need help  :(((((**

**Comment by JustZacca** [comment]
Nothing, just one name written in cyrillic.
