### ISSUE TITLE
Loading an Excel 2007 spreadsheet results in a PHP Fatal Error

### ISSUE THREAD

**Issue by kanduvisla** [PHPOffice/PhpSpreadsheet#184]
When I try to load an Excel 2007 spreadsheet using the most basic approach I get a PHP Fatal Error.

What I'm trying is:

```php
$spreadSheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('sheet.xlsx');
```

The resulting error:

```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PhpOffice\PhpSpreadsheet\Reader\Excel2007::readStyle() must be an instance of stdClass, instance of SimpleXMLElement given, called in /vagrant/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Excel2007.php on line 630 and defined in /vagrant/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Excel2007.php:1880
Stack trace:
#0 /vagrant/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Excel2007.php(630): PhpOffice\PhpSpreadsheet\Reader\Excel2007::readStyle(Object(PhpOffice\PhpSpreadsheet\Style), Object(SimpleXMLElement))
#1 /vagrant/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/IOFactory.php(175): PhpOffice\PhpSpreadsheet\Reader\Excel2007->load('/vagrant/var/Ar...')
#2 /vagrant/app/code/xxx/Import/Model/ExcelManagement.php(45): PhpOffice\PhpSpreadsheet\IOFactory::load('/vagrant/var/Ar...')
#3 /vagrant/app/code/xxx/Import/Console/ValidateExcel.php(68): xxx\Import\Model\ExcelManagement->loadExcelFile('/vagrant/var/Ar...')
#4  in /vagrant/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Excel2007.php on line 1880
```

**Comment by PowerKiKi** [comment]
Please fill out the required fields when submitting an issue.
