### ISSUE TITLE
Can't save an Xlsx file with images twice with the same name

### ISSUE THREAD

**Issue by DiogoMestre** [PHPOffice/PhpSpreadsheet#1910]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
An xlsx file with images can be saved several times with the same name, without errors occurring.

### What is the current behavior?
When we try to save a file with images, that already exists with the same name, an error occurs.
```
PHP Fatal error:  Uncaught PhpOffice\PhpSpreadsheet\Writer\Exception: File zip://C:\Users\diogo\Documents\PhpSpreadsheet\test.xlsx#xl/media/54b0c99f8d2c2a408c3a8abee180cd941.png does not exist in C:\Users\diogo\Documents\PhpSpreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\ContentTypes.php:198
Stack trace:
#0 C:\Users\diogo\Documents\PhpSpreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\ContentTypes.php(126): PhpOffice\PhpSpreadsheet\Writer\Xlsx\ContentTypes->getImageMimeType()
#1 C:\Users\diogo\Documents\PhpSpreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx.php(216): PhpOffice\PhpSpreadsheet\Writer\Xlsx\ContentTypes->writeContentTypes()
#2 C:\Users\diogo\Documents\PhpSpreadsheet\BugReport.php(30): PhpOffice\PhpSpreadsheet\Writer\Xlsx->save()
#3 {main}
  thrown in C:\Users\diogo\Documents\PhpSpreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\ContentTypes.php on line 198
```

### What are the steps to reproduce?
1) Create an Xlsx file with images.
2) Save this file.
3) Load the file;
4) Save it again with the same name.
 
Note: I'm using the same code used by @PowerKiKi  in this comment [https://github.com/PHPOffice/PhpSpreadsheet/issues/544#issuecomment-427643848](https://github.com/PHPOffice/PhpSpreadsheet/issues/544#issuecomment-427643848). The unique difference is that I'm saving the second Xlsx file with the same name as the first file.

```php
<?php
require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Worksheet\MemoryDrawing;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Create new Spreadsheet object
$spreadsheet = new Spreadsheet();

// Generate an image
$gdImage = imagecreatetruecolor(250, 30);
$textColor = imagecolorallocate($gdImage, 255, 255, 255);
imagestring($gdImage, 4, 5, 5, 'Created with PhpSpreadsheet', $textColor);

// Add a drawing to the worksheet
$drawing = new MemoryDrawing();
$drawing->setImageResource($gdImage);
$drawing->setWorksheet($spreadsheet->getActiveSheet());

$writer = new Xlsx($spreadsheet);
$writer->save('test.xlsx');

$reloaded = IOFactory::load('test.xlsx');

$reloaded->getActiveSheet()->setCellValue('D5', 'foo');

$writer = new Xlsx($reloaded);
$writer->save('test.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: v1.17.1
PHP: v7.4.13;

**Comment by DiogoMestre** [comment]
Created 2 duplicated tickets. https://github.com/PHPOffice/PhpSpreadsheet/issues/1911
