### ISSUE TITLE
Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Worksheet!C19981 -> Formula Error: 

### ISSUE THREAD

**Issue by djeraseit** [PHPOffice/PhpSpreadsheet#294]
This is:

- [ ] a bug report

### What is the expected behavior?

Data is read successfully. Simple CSV. Should not be doing any calculations

### What is the current behavior?

It hiccups partway through the file

```
PHP Fatal error:  Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Worksheet!C19981 -> Formula Error: An unexpected error occured in /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php:273
Stack trace:
#0 /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(2551): PhpOffice\PhpSpreadsheet\Cell\Cell->getCalculatedValue()
#1 /l/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(2626): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->rangeToArray('A1:AY20099', NULL, true, true, true)
#2 //includes/functions.php(1009): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->toArray(NULL, true, true, true)
#3 /includes/import-single-spreadsheet.php(53): importCSV('xxxx', 'https://www.who...')
#4 {main}
  in /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php on line 273

Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Worksheet!C19981 -> Formula Error: An unexpected error occured in /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php:273
Stack trace:
#0 /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(2551): PhpOffice\PhpSpreadsheet\Cell\Cell->getCalculatedValue()
#1 /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(2626): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->rangeToArray('A1:AY20099', NULL, true, true, true)
#2 /public_html/includes/functions.php(1009): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->toArray(NULL, true, true, true)
#3 //includes/import-single-spreadsheet.php(53): importCSV('xxxx', 'https://www.who...')
#4 {main}
  in /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php on line 273
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

try {
$spreadsheet = $reader->load($filename);
} catch(\PhpOffice\PhpSpreadsheet\Reader\Exception $e) {
    die('Error loading file: '.$e->getMessage());
}

    //  Do some processing here
$rows = $spreadsheet->getActiveSheet()->toArray(null, true, true, true);
    // var_dump($rows);


```

### Which versions of PhpSpreadsheet and PHP are affected?
php 7.0

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue without relying on an external Excel file.
