### ISSUE TITLE
Removing a column with cells within a range of Table causes a type error

### ISSUE THREAD

**Issue by adawolfa** [PHPOffice/PhpSpreadsheet#3310]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

`Worksheet::removeColumnByIndex()` not crashing.

### What is the current behavior?

`Worksheet::removeColumnByIndex()` crashes with:

~~~
Fatal error: Uncaught TypeError: PhpOffice\PhpSpreadsheet\Worksheet\Table\Column::updateStructuredReferences(): Argument #3 ($newTitle) must be of type string, null given, called in vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Cell\Cell.php on line 210 and defined in vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Worksheet\Table\Column.php:208
Stack trace:
#0 vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Cell\Cell.php(210): PhpOffice\PhpSpreadsheet\Worksheet\Table\Column::updateStructuredReferences(Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), 'foo', NULL)
#1 vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Cell\Cell.php(302): PhpOffice\PhpSpreadsheet\Cell\Cell::updateIfCellIsTableHeader(Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), Object(PhpOffice\PhpSpreadsheet\Cell\Cell), 'foo', NULL)
#2 vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\ReferenceHelper.php(1011): PhpOffice\PhpSpreadsheet\Cell\Cell->setValueExplicit(NULL, 'null')
#3 vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\ReferenceHelper.php(985): PhpOffice\PhpSpreadsheet\ReferenceHelper->clearStripCell(Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), 'C1')
#4 vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\ReferenceHelper.php(403): PhpOffice\PhpSpreadsheet\ReferenceHelper->clearColumnStrips(2, 4, -1, Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet))
#5 vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Worksheet\Worksheet.php(2528): PhpOffice\PhpSpreadsheet\ReferenceHelper->insertNewBefore('D1', -1, 0, Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet))
#6 vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Worksheet\Worksheet.php(2579): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->removeColumn('D', 1)
#7 test.php(16): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->removeColumnByIndex(3)
#8 {main}
  thrown in vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Worksheet\Table\Column.php on line 208
~~~

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Table;

require(__DIR__ . '/vendor/autoload.php');

$spreadsheet = new Spreadsheet;
$sheet = $spreadsheet->getActiveSheet();

$sheet->addTable(new Table('A1:D2'));

$sheet->setCellValue('C1', 'foo');
$sheet->setCellValue('C2', 'bar');

$sheet->removeColumnByIndex(3);
```

### Which versions of PhpSpreadsheet and PHP are affected?

1.26 (tested on 8.2, but likely failing in 7.4 as well), I believe caused by #3236.

**Comment by MarkBaker** [comment]
This should have been resolved by [PR #3311](https://github.com/PHPOffice/PhpSpreadsheet/pull/3311)
