### ISSUE TITLE
Failure to calculate cell with specific nested IF conditions

### ISSUE THREAD

**Issue by tony-clariondoor** [PHPOffice/PhpSpreadsheet#3755]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
A cell with a moderately complex formula should evaluate to `0` based upon the logic provided which is the `else` condition in the formula described below.

### What is the current behavior?
Calculation of a cell yields a internal error with Exception code 0 and throws that exception with a stack trace that doesn't provide a ton of insight.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheetFile = "test.xml";
$brokenCell = "F10";
// loading the file
$workbook = IOFactory::load($spreadsheetFile);
$calcVal = $workbook->getActiveSheet()->getCell($brokenCell)->getCalculatedValue(); // <== here is the failure

// Only useful part of the stack trace that didn't reference Laravel Routing libraries:
// [2023-09-29 17:38:37] local.ERROR: Sheet1!F10 -> internal error {"exception":"[object] (PhpOffice\\PhpSpreadsheet\\Calculation\\Exception(code: 0): Sheet1!F10 -> internal error at /var/www/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php:397)
// [stacktrace]
// #0 /var/www/app/Http/Controllers/SpreadsheetController.php(75): PhpOffice\\PhpSpreadsheet\\Cell\\Cell->getCalculatedValue()
// #1 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\SpreadsheetController->calculate(Object(Illuminate\\Http\\Request))
// 44 other lines omitted as they aren't a part of this

```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

The formula that failed the first time if this:

`IF(B19=1,IF(AND(IF(E831>0,E831,IF(F830=0,(E830*G1330),F830))>0,IF(E831>0,E831,IF(F830=0,(E830*G1330),F830))<1),1,ROUND(IF(E831>0,E831,IF(F830=0,(E830*G1330),F830)),0)),0)`

And this `ONLY` fails when cell B19 is not equal to 1. I pared it down to take out all the cells within the true condition and it still fails with minimal output into the stack trace. Paring it down, the formula looked like:

`IF(B19=1,IF(AND(IF(1>0,1,IF(0=0,(0*0),0))>0,IF(0>0,0,IF(0=0,(0*0),0))<1),1,ROUND(IF(0>0,0,IF(1=0,(1*1),1)),0)),0)`

and it still failed without additional information provided. 

If I take the `iftrue` part out of the first `IF` function and put it into another cell and then point to that cell it calculates correctly despite it never being used in either case. 

I do have a viable workaround, but I am concerned that there is a nested function parsing problem that will rear up in random ways with complex formulas (I am in the insurance industry and some analysts seem to be in a competition to write the most complex Excel formulas they possibly can) and I hope that this pared down example (with cited workaround) can either be something investigated or at least logged so somebody else perusing the issues list will see it and at least get up and running until it is found. 

I tried this in PHP 8.0 and with 8.2, as well as multiple versions of PhpSpreadsheet (current and the last three) to make sure I wasn't seeing a newly introduced bug. 

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [X] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
It seems to break on calculate regardless of the file format (that supports these functions). 

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 8.0 and PHP 8.2
PhpSpreadsheet 1.27, 1.27.1, 1.28, 1.29

**Comment by tony-clariondoor** [comment]
Tried looking into this again with PHP 8.3 and PHPSpreadsheet 2.1.0 and I may have found something. 

in `src/PhpSpreadsheet/Calculation/Engine/BranchPruner.php` the function `initialiseCondition()` seems to be setting the `previousStoreKey` variable to a `ROUND` when it means to set it to an `IF` in the stack. It might be thrown with the `closingBrace()` method because it throws exceptions in the case of it not being an `IF` function and in the case of the existence of a `pendingStoreKey`. 

The good news is that in both 2.0 and 2.1.0 Adding:

```
$calcEngine = Calculation::getInstance($workbook);
$calcEngine->disableBranchPruning();
```

prior to running a `getCalculatedValue()` does in fact stop the unhandled exception from occurring. It did not work in my attempts with previous versions despite all signs indicating that it should have.

**Comment by beneverard** [comment]
I've experienced the same issue on 1.29.7, and disabling branch pruning fixed this for me also, thanks @tony-clariondoor.
