### ISSUE TITLE
Problem with load file

### ISSUE THREAD

**Issue by plehanov** [PHPOffice/PhpSpreadsheet#385]
This is:

```
- [ x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$type = IOFactory::identify($requiredFile);
$reader = IOFactory::createReader($type);
$spreadsheet = $reader->load($requiredFile);

// add code that show the issue here...
Undefined offset: 0 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 0 at /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php:3632)
[stacktrace]
#0 /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php(3632): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/home/takamura/...', 3632, Array)
#1 /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php(936): PhpOffice\\PhpSpreadsheet\\Reader\\Xls->readColInfo()
#2 MyProvider.php(377): PhpOffice\\PhpSpreadsheet\\Reader\\Xls->load('/home/takamura/...')

```

### Which versions of PhpSpreadsheet and PHP are affected?
1.1.0

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue **without relying on an external Excel file** or a web server.
