### ISSUE TITLE
HYPERLINK function not working correctly when you try to link a cell to another spreadsheet

### ISSUE THREAD

**Issue by DarkTiBe** [PHPOffice/PhpSpreadsheet#56]
When you set the content of a cell to =HYPERLINK("#anotherspreadshet!A1","link") the class throws the next Fatal error:
```

Uncaught exception 'PhpOffice\PhpSpreadsheet\Calculation\Exception' with message 'anotherspreadshet!A1 -> Formula Error: An unexpected error occured' in \src\PhpSpreadsheet\Cell.php:280
Stack trace:
#0 src\PhpSpreadsheet\Writer\Xlsx\Worksheet.php(1080): PhpOffice\PhpSpreadsheet\Cell->&gt;getCalculatedValue()
#1 src\PhpSpreadsheet\Writer\Xlsx\Worksheet.php(1027): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeCell(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), Object(PhpOffice\PhpSpreadsheet\Worksheet), 'A1', Array, Array)
#2 src\PhpSpreadsheet\Writer\Xlsx\Worksheet.php(80): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeSheetData(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), Object(PhpOffice\PhpSpreadsheet\Worksheet), Array)
#3 srcl\PhpSpreadsheet\W src\Cell.php on line 280

```

**Comment by MarkBaker** [comment]
Nasty, nasty Microsoft.... they changed the syntax for inter-sheet references between formats.

For xls, the syntax is `sheet://anotherspreadshet!A1`; for xlsx, they changed it to `#anotherspreadshet!A1`

Will need to take a closer look at handling this, and it's made more awkward by using it in a formula

**Comment by oleibman** [comment]
Sometime between 7-odd years ago when this issue was marked stale and now, it was resolved. It happened so long ago that I can't even point to specific fix. Oddly, however, the issue was reported against Xlsx, and the commentary suggests that Xls was behaving. However, it seems to me that Xls is not working correctly, so I am reopening the issue, to be closed when I submit a PR to fix it, which I will do shortly.
