### ISSUE TITLE
Cell coordinate string can not be a range of cells

### ISSUE THREAD

**Issue by three72** [PHPOffice/PhpSpreadsheet#58]
Getting this when writing to xlsx file. I guess it is only happening when there are some charts on some other worksheets.

```
PHP Fatal error:  Uncaught exception 'PhpOffice\PhpSpreadsheet\Exception' with message 'Cell coordinate string can not be a range of cells' in /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/src/PhpSpreadsheet/Cell.php:577
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xls/Worksheet.php(4195): PhpOffice\PhpSpreadsheet\Cell::coordinateFromString('S147:S151')
#1 /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xls/Worksheet.php(502): PhpOffice\PhpSpreadsheet\Writer\Xls\Worksheet->writeCFHeader()
#2 /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xls.php(173): PhpOffice\PhpSpreadsheet\Writer\Xls\Worksheet->close()
#3 /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/samples/csv_to_xsl.php(139): PhpOffice\PhpSpreadsheet\Writer\Xls->save('/Applications/X...')
#4 /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/samples/csv_to_xsl.php(56): writeToSpreedshe in /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/src/PhpSpreadsheet/Cell.php on line 577

Fatal error: Uncaught exception 'PhpOffice\PhpSpreadsheet\Exception' with message 'Cell coordinate string can not be a range of cells' in /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/src/PhpSpreadsheet/Cell.php:577
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xls/Worksheet.php(4195): PhpOffice\PhpSpreadsheet\Cell::coordinateFromString('S147:S151')
#1 /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xls/Worksheet.php(502): PhpOffice\PhpSpreadsheet\Writer\Xls\Worksheet->writeCFHeader()
#2 /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xls.php(173): PhpOffice\PhpSpreadsheet\Writer\Xls\Worksheet->close()
#3 /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/samples/csv_to_xsl.php(139): PhpOffice\PhpSpreadsheet\Writer\Xls->save('/Applications/X...')
#4 /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/samples/csv_to_xsl.php(56): writeToSpreedshe in /Applications/XAMPP/xamppfiles/htdocs/phpspread/PhpSpreadsheet/src/PhpSpreadsheet/Cell.php on line 577
```

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue. And don't forget to mention what version of this project you are using. That way there will be more chance for the issue to be re-opened and solved.
